version: '3.7'

services:

  digitalse-cbm-ocr:
    container_name: digitalse-cbm-ocr
    environment:
      - SECRET
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3306:8083'
      
networks:
  default:
    external: true
    name: internal