server:
    port: 9083

tesseract:
    datapath: src/main/resources/tess/tessdata
    language: por

spring:
    servlet:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
